### PR TITLE
Moving organization details to footer

### PR DESCRIPTION
**Pull request by bhavyasinghal06**

### CODE REVIEW

**Comment by sammy1997** [comment]
@bhavyasinghal06 please provide a description and rebase your branch. There are so many commits!

**Comment by Eshaan7** [comment]
Yes. Please rebase your branch, otherwise the project's history will get broken. Here's a guide on squashing commits: https://github.com/wprig/wprig/wiki/How-to-squash-commits

**Comment by bhavyasinghal06** [comment]
@sammy1997 I have made the pull request "Moving organisation details to footer"(#29).

**Comment by Eshaan7** [comment]
Will check it soon. Thanks, @bhavyasinghal06

**Pull request closed without merging**
