### PR TITLE
Added travis integration

### PR DESCRIPTION
**Pull request by illseption**
Changes:
- Added .travis.yml file

The build is currently failing and this might need to be fixed in another issue

### CODE REVIEW

**Comment by sammy1997** [comment]
Hey @illseption ! I see that you are using .sh scripts from a project. We can't ensure the trustability of the source and also don't know if it's regularly maintained. I would suggest adding the required steps in the .yml itself than running a bash script from another project. @Eshaan7 Thoughts?

**Comment by illseption** [comment]
Okay, what tests should I add? I'm calling the other project because it provides easy linting of the code. We could maybe use coala if maintenance is an issue?

**Comment by sammy1997** [comment]
I meant that you can directly add the dependencies and installation commands in travis yml file. We don't need a separate service for that

**Comment by Eshaan7** [comment]
I don't think there's a problem with using the script from another git. If any issue comes in the feature, we can handle it then. So I will be merging this now.

**Pull request merged**
